apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hashing-apis-v2
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-hashing-apis-v2
  template:
    metadata:
      labels:
        app: cloud-hashing-apis-v2
    spec:
      containers:
      - name: cloud-hashing-apis-v2
        image: uhub.service.ucloud.cn/entropypool/cloud-hashing-apis-v2:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CURRENCY_REQUEST_PROXY
          valueFrom:
            configMapKeyRef:
              name: currency-proxy-environment
              key: environment.currency_proxy
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-hashing-apis-v2
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50140
    targetPort: 50140
  selector:
    app: cloud-hashing-apis-v2
