apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloud-hashing-apis-v2-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: cloud-hashing-apis-v2-traefik-app-user
    k8s.kuboard.cn/workload: cloud-hashing-apis-v2-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-cloud-hashing-apis-v2-prefix@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd,
                                                      kube-system-headers-appid-to-body@kubernetescrd,
                                                      kube-system-headers-userid-to-body@kubernetescrd,
                                                      kube-system-headers-langid-to-body@kubernetescrd,
                                                      kube-system-headers-app-login-token-to-body@kubernetescrd,
                                                      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/cloud-hashing-apis-v2/v1/create/good
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/submit/order
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/submit/user/order
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/submit/app/user/order
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/submit/user/withdraw
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/order/payment
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/order
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/orders/by/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/referrals
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/user/referrals
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/kyc/reviews
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/good/reviews
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/kyc/by/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/kyc
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/kyc
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/password/by/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/emailaddress
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/phoneno
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/account
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/platform/coin/account
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/user/coin/account
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/set/withdraw
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/delete/withdraw
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/withdraw
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/user/withdraw
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/coupons
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/commission
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/current/fee
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/amount/settings
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/invitation/code
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/amount/setting
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
    - host: api.procyon.vip
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.ohhash-production.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.jh-development.npool.top
      http: *http_rules
    - host: api.singapore-testing.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloud-hashing-apis-v2-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: cloud-hashing-apis-v2-traefik-app
    k8s.kuboard.cn/workload: cloud-hashing-apis-v2-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-cloud-hashing-apis-v2-prefix@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd,
                                                      kube-system-headers-appid-to-body@kubernetescrd,
                                                      kube-system-headers-userid-to-body@kubernetescrd,
                                                      kube-system-headers-app-login-token-to-body@kubernetescrd,
                                                      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/cloud-hashing-apis-v2/v1/get/good
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/goods
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/recommend/goods/by/app
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/signup
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/update/password
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/version
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
    - host: api.procyon.vip
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.ohhash-production.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.jh-development.npool.top
      http: *http_rules
    - host: api.singapore-testing.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
