apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloud-hashing-apis-v2-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: cloud-hashing-apis-v2-traefik-app-user
    k8s.kuboard.cn/workload: cloud-hashing-apis-v2-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-cloud-hashing-apis-v2-prefix@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd,
                                                      kube-system-headers-appid-to-body@kubernetescrd,
                                                      kube-system-headers-userid-to-body@kubernetescrd,
                                                      kube-system-headers-langid-to-body@kubernetescrd,
                                                      kube-system-headers-app-login-token-to-body@kubernetescrd,
                                                      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/cloud-hashing-apis-v2/v1/get/withdraw/address/reviews/by/app
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/withdraw/address/reviews/by/other/app
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/withdraw/address/reviews/by/app
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/amount/setting
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/amount/settings
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/current/fee
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/withdraw/addresses/by/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/delete/withdraw/address
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/set/withdraw/address
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/user/coin/account
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/platform/coin/account
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path:  /api/cloud-hashing-apis-v2/v1/get/withdraw/addresses/by/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path:  /api/cloud-hashing-apis-v2/v1/get/withdraw/addresses/by/app/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path:  /api/cloud-hashing-apis-v2/v1/set/withdraw/address
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path:  /api/cloud-hashing-apis-v2/v1/delete/withdraw/address
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path:  /api/cloud-hashing-apis-v2/v1/get/withdraw/address/reviews/by/app
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path:  /api/cloud-hashing-apis-v2/v1/get/withdraw/address/reviews/by/other/app
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/coupons
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/commission
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/user
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/current/fee
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/get/amount/settings
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/invitation/code
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
          - path: /api/cloud-hashing-apis-v2/v1/create/amount/setting
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140

    - host: api.procyon.vip
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.ohhash-production.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.jh-development.npool.top
      http: *http_rules
    - host: api.singapore-testing.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloud-hashing-apis-v2-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: cloud-hashing-apis-v2-traefik-app
    k8s.kuboard.cn/workload: cloud-hashing-apis-v2-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-cloud-hashing-apis-v2-prefix@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd,
                                                      kube-system-headers-appid-to-body@kubernetescrd,
                                                      kube-system-headers-userid-to-body@kubernetescrd,
                                                      kube-system-headers-app-login-token-to-body@kubernetescrd,
                                                      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/cloud-hashing-apis-v2/version
            backend:
              serviceName: cloud-hashing-apis-v2
              servicePort: 50140
    - host: api.procyon.vip
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.ohhash-production.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.jh-development.npool.top
      http: *http_rules
    - host: api.singapore-testing.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
